### ISSUE TITLE
Permission denied error running locally

### ISSUE THREAD

**Issue by jlewi** [fastai/fastpages#370]
## Required information

1. Steps to reproduce the problem

```
make server
```

2. A link to the notebook or markdown file where the error is occurring
3. If the error is happening in GitHub Actions, a link to the specific error along with how you are able to reproduce this error.  You must provide this **in addition to the link to the notebook or markdown file**.
4. A screenshot / dump of relevant logs or error messages you are receiving from your local development environment. Instructions of running a local development server is provided in the [development guide](https://github.com/fastai/fastpages/blob/master/_fastpages_docs/DEVELOPMENT.md).

When trying to run the server locally I'm getting

```
jekyll_1     | Successfully installed bundler-2.1.4
jekyll_1     | 1 gem installed
jekyll_1     | ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     | /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /data/.jekyll-cache (Errno::EACCES)
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:250:in `fu_mkdir'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:228:in `block (2 levels) in mkdir_p'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `reverse_each'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:226:in `block in mkdir_p'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `each'
jekyll_1     | 	from /usr/local/lib/ruby/2.7.0/fileutils.rb:211:in `mkdir_p'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/cache.rb:184:in `dump'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/cache.rb:101:in `[]='
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/cache.rb:45:in `clear_if_config_changed'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:113:in `reset'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/site.rb:33:in `initialize'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:30:in `new'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:30:in `process'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
jekyll_1     | 	from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
jekyll_1     | 	from /usr/gem/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
jekyll_1     | 	from /usr/local/bundle/bin/jekyll:29:in `load'
jekyll_1     | 	from /usr/local/bundle/bin/jekyll:29:in `<main>'
git_kubeflow-blog_jekyll_1 exited with code 1
```

**Comment by jlewi** [comment]
IIUC  container is volume mounting the files from my local filesystem and it is likely causing problems.

An approach I commonly for development is to use skaffold to deploy a server on K8s and then scp files to the pod for hot reloading.

That might indirectly solve this problem.
