### ISSUE TITLE
Problem with remote-theme

### ISSUE THREAD

**Issue by goodboychan** [fastai/fastpages#551]
Hi,

Currently, I faced with this build fail error in fastpages.
I don't know much details about ruby, but problem is occurred while cleaning up jekyll remote-theme.
(Actually, this problem doesn't happen in 2 days ago.)

Here is detailed build log.

```shell
Liquid Exception: undefined method `add_previous_sibling' for nil:NilClass in /github/workspace/_layouts/post.html
      Remote Theme: Cleaning up /tmp/jekyll-remote-theme-20210614-1-tooew5
/usr/gem/gems/jekyll-toc-0.14.0/lib/table_of_contents/parser.rb:28:in `block in inject_anchors_into_html': undefined method `add_previous_sibling' for nil:NilClass (NoMethodError)
	from /usr/gem/gems/jekyll-toc-0.14.0/lib/table_of_contents/parser.rb:26:in `each'
	from /usr/gem/gems/jekyll-toc-0.14.0/lib/table_of_contents/parser.rb:26:in `inject_anchors_into_html'
	from /usr/gem/gems/jekyll-toc-0.14.0/lib/table_of_contents/parser.rb:18:in `toc'
	from /usr/gem/gems/jekyll-toc-0.14.0/lib/jekyll-toc.rb:37:in `toc'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/strainer.rb:56:in `invoke'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/context.rb:86:in `invoke'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/variable.rb:84:in `block in render'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `each'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `inject'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/variable.rb:82:in `render'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:103:in `render_node_to_output'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:80:in `render'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:208:in `block in render'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:242:in `with_profiling'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:207:in `render'
	from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:220:in `render!'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:39:in `block (3 levels) in render!'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:59:in `measure_counts'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:38:in `block (2 levels) in render!'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:63:in `measure_bytes'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:37:in `block in render!'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:70:in `measure_time'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/liquid_renderer/file.rb:36:in `render!'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:127:in `render_liquid'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:190:in `render_layout'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:159:in `place_in_layouts'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:89:in `render_document'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/renderer.rb:63:in `run'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:532:in `render_regenerated'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:517:in `block (2 levels) in render_docs'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:516:in `each'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:516:in `block in render_docs'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:515:in `each_value'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:515:in `render_docs'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:207:in `render'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/site.rb:80:in `process'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:28:in `process_site'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:65:in `build'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:36:in `process'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `each'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
	from /usr/gem/gems/jekyll-4.1.1/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
	from /usr/gem/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
	from /usr/gem/gems/jekyll-4.1.1/exe/jekyll:15:in `<top (required)>'
	from /usr/local/bundle/bin/jekyll:29:in `load'
	from /usr/local/bundle/bin/jekyll:29:in `<main>'
```

I tried to google this kind of problems, but didn't get any clues... Should I wait until it is fixed?

Thanks in advance.

**Comment by goodboychan** [comment]
Nevermind. It's related on toc style conflict.

Thanks.
