### ISSUE TITLE
Failed to set up locally in M1 Mac

### ISSUE THREAD

**Issue by riven314** [fastai/fastpages#615]
here is my fastpage repo: [https://github.com/riven314/alexlauwh](https://github.com/riven314/alexlauwh)
I tried building it locally in my M1 Macbook by `make server`, but got the following error:
```
❯ make server
docker-compose down --remove-orphans || true;
Removing alexlauwh_converter_1 ... done
Removing alexlauwh_jekyll_1    ... done
Removing alexlauwh_fastpages_1 ... done
Removing alexlauwh_watcher_1   ... done
Removing network alexlauwh_default
docker-compose up
Creating network "alexlauwh_default" with the default driver
Creating alexlauwh_jekyll_1    ... done
Creating alexlauwh_converter_1 ... done
Creating alexlauwh_watcher_1   ... done
Creating alexlauwh_fastpages_1 ... done
Attaching to alexlauwh_watcher_1, alexlauwh_fastpages_1, alexlauwh_converter_1, alexlauwh_jekyll_1
converter_1  | Agent pid 11
converter_1  | === Running Locally: All assets expected to be in the directory /data ===
fastpages_1  | Agent pid 13
fastpages_1  | === Running Locally: All assets expected to be in the directory /data ===
watcher_1    | Traceback (most recent call last):
watcher_1    |   File "/usr/local/bin/watchmedo", line 8, in <module>
watcher_1    |     sys.exit(main())
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 576, in main
watcher_1    |     parser.dispatch()
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/argh/helpers.py", line 55, in dispatch
watcher_1    |     return dispatch(self, *args, **kwargs)
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 174, in dispatch
watcher_1    |     for line in lines:
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 277, in _execute_command
watcher_1    |     for line in result:
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/argh/dispatching.py", line 231, in _call
watcher_1    |     result = function(namespace_obj)
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 447, in shell_command
watcher_1    |     observe_with(observer, handler, args.directories, args.recursive)
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/watchmedo.py", line 116, in observe_with
watcher_1    |     observer.start()
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/api.py", line 260, in start
watcher_1    |     emitter.start()
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 110, in start
watcher_1    |     self.on_thread_start()
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start
watcher_1    |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
watcher_1    |     self._inotify = Inotify(path, recursive)
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 189, in __init__
watcher_1    |     Inotify._raise_error()
watcher_1    |   File "/usr/local/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 432, in _raise_error
watcher_1    |     raise OSError(err, os.strerror(err))
watcher_1    | OSError: [Errno 38] Function not implemented
```

When it said the server is running and I tried to navigate to https://127.0.0.1:4000, I got the following error in terminal:
```
jekyll_1     |  Auto-regeneration: enabled for '/data'
jekyll_1     |     Server address: http://0.0.0.0:4000/alexlauwh/
jekyll_1     |   Server running... press ctrl-c to stop.
jekyll_1     | [2022-01-24 20:19:46] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03`.*�|\b�X\x00�6w\x15�Pϱ�8\tX^�\x12e��R�2�� ������Y`l��\x1E���ZKDv��A\x0E���)�\e���\x00 **\x13\x01\x13\x02\x13\x03�+�/�,�0̨̩�\x13�\x14\x00�\x00�\x00/\x005\x01\x00\x01�JJ\x00\x00\x00\x17\x00\x00�\x01\x00\x01\x00\x00'.
jekyll_1     | [2022-01-24 20:19:46] ERROR bad URI `�p#b���,K\x197�'.
jekyll_1     | [2022-01-24 20:19:46] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03�\x17\x1D\x1D��y\x11p�+u�"?��\fI�Z�;���͐\f S\x16�nG��\x15�R\x10.�\v>\x15}�����\x03�\x02�3*�� �\x00 JJ\x13\x01\x13\x02\x13\x03�+�/�,�0̨̩�\x13�\x14\x00�\x00�\x00/\x005\x01\x00\x01���\x00\x00\x00\x17\x00\x00�\x01\x00\x01\x00\x00'.
jekyll_1     | [2022-01-24 20:19:46] ERROR bad Request-Line `\x16\x03\x01\x02\x00\x01\x00\x01�\x03\x03:�Ue�Wq\\%�\x13���ʐ�\x13\x1D�R�\x1CM\x19\x1F��>�� v�F�\x04\x1D}�6�J� �\x06��U��?z`��)�߼�N�\x00 '.
```

Any M1 user encountered the same issue?

**Comment by riven314** [comment]
it's solved by using the updated fastpage repo

**Comment by andretavare5** [comment]
fresh clone did not solve it for me https://github.com/fastai/fastpages/issues/646

**Comment by farlandliu** [comment]
I have the same error message on M1 iMac.
I have tried to deleted `Gemfile.lock`,re-builded the images and  rendered ok.

```shell
➜  blog git:(master) ✗ make server
chmod -R u+rw .
docker-compose down --remove-orphans || true;
Removing blog_converter_1 ... done
Removing blog_notebook_1  ... done
Removing blog_watcher_1   ... done
Removing blog_jekyll_1    ... done
Removing blog_fastpages_1 ... done
Removing network blog_default
docker-compose up
Creating network "blog_default" with the default driver
Creating blog_jekyll_1    ... done
Creating blog_watcher_1   ... done
Creating blog_converter_1 ... done
Creating blog_fastpages_1 ... done
Creating blog_notebook_1  ... done
Attaching to blog_watcher_1, blog_jekyll_1, blog_fastpages_1, blog_converter_1, blog_notebook_1
watcher_1    | Traceback (most recent call last):
watcher_1    |   File "/usr/local/bin/watchmedo", line 8, in <module>
watcher_1    |     sys.exit(main())
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/watchmedo.py", line 581, in main
watcher_1    |     parser.dispatch()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/helpers.py", line 55, in dispatch
watcher_1    |     return dispatch(self, *args, **kwargs)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/dispatching.py", line 174, in dispatch
watcher_1    |     for line in lines:
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/dispatching.py", line 277, in _execute_command
watcher_1    |     for line in result:
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/dispatching.py", line 231, in _call
watcher_1    |     result = function(namespace_obj)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/watchmedo.py", line 442, in shell_command
watcher_1    |     observe_with(observer, handler, args.directories, args.recursive)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/watchmedo.py", line 111, in observe_with
watcher_1    |     observer.start()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/api.py", line 256, in start
watcher_1    |     emitter.start()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/utils/__init__.py", line 93, in start
watcher_1    |     self.on_thread_start()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify.py", line 117, in on_thread_start
watcher_1    |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
watcher_1    |     self._inotify = Inotify(path, recursive)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 186, in __init__
watcher_1    |     Inotify._raise_error()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 429, in _raise_error
watcher_1    |     raise OSError(err, os.strerror(err))
watcher_1    | OSError: [Errno 38] Function not implemented
fastpages_1  | Agent pid 11
converter_1  | Agent pid 11
blog_watcher_1 exited with code 1
fastpages_1  | === Running Locally: All assets expected to be in the directory /data ===
converter_1  | === Running Locally: All assets expected to be in the directory /data ===
fastpages_1  | converting: _notebooks/2020-02-20-test.ipynb
notebook_1   | [I 08:09:06.958 NotebookApp] Writing notebook server cookie secret to /root/.local/share/jupyter/runtime/notebook_cookie_secret
converter_1  | converting: _notebooks/2020-02-20-test.ipynb
notebook_1   | [W 08:09:07.836 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
notebook_1   | [I 08:09:07.849 NotebookApp] Serving notebooks from local directory: /data
notebook_1   | [I 08:09:07.849 NotebookApp] Jupyter Notebook 6.1.6 is running at:
notebook_1   | [I 08:09:07.850 NotebookApp] http://3d273cae62a2:8080/
notebook_1   | [I 08:09:07.850 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
blog_fastpages_1 exited with code 0
blog_converter_1 exited with code 0
jekyll_1     | Fetching gem metadata from https://rubygems.org/.......
jekyll_1     | Fetching concurrent-ruby 1.1.10
jekyll_1     | Installing concurrent-ruby 1.1.10
jekyll_1     | Fetching i18n 1.10.0
jekyll_1     | Installing i18n 1.10.0
jekyll_1     | Fetching minitest 5.16.1
jekyll_1     | Installing minitest 5.16.1
jekyll_1     | Using thread_safe 0.3.6
...
...
jekyll_1     | Installing ffi 1.15.5 with native extensions
jekyll_1     | Using forwardable-extended 2.6.0
jekyll_1     | Using gemoji 3.0.1
jekyll_1     | Fetching mini_portile2 2.8.0
jekyll_1     | Installing mini_portile2 2.8.0
jekyll_1     | Fetching racc 1.6.0
jekyll_1     | Installing racc 1.6.0 with native extensions
jekyll_1     | Fetching nokogiri 1.13.6 (x86_64-linux)
jekyll_1     | Bundle complete! 18 Gemfile dependencies, 59 gems now installed.
jekyll_1     | Use `bundle info [gemname]` to see where a bundled gem is installed.
jekyll_1     | ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-musl]
jekyll_1     | Configuration file: /data/_config.yml
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |             Source: /data
jekyll_1     |        Destination: /data/_site
jekyll_1     |  Incremental build: disabled. Enable with --incremental
jekyll_1     |       Generating...
jekyll_1     |       Remote Theme: Using theme jekyll/minima
jekyll_1     |        Jekyll Feed: Generating feed for posts

```

**Comment by alexlenail** [comment]
Could someone report the best way to solve this issue? I've heavily modified the templates / styles, so don't want to move notebooks to a fresh fastpages instance if possible. I recently switched to M1 and can't build my blog locally anymore -- it still builds via the github action though.

```
...
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 432, in _raise_error
watcher_1    |     raise OSError(err, os.strerror(err))
watcher_1    | OSError: [Errno 38] Function not implemented
```
