### ISSUE TITLE
Failed to set up locally in M1 Mac

### ISSUE THREAD

**Issue by andretavare5** [fastai/fastpages#646]
Similar to https://github.com/fastai/fastpages/issues/615

A few minutes ago I cloned fastpages repo and tried building it locally in my M1 Macbook by make server, but got the following error:

```
❯ make server
chmod -R u+rw .
docker-compose down --remove-orphans || true;
Stopping fastpages_converter_1 ... done
Removing fastpages_notebook_1  ... done
Removing fastpages_jekyll_1    ... done
Removing fastpages_watcher_1   ... done
Removing fastpages_converter_1 ... done
Removing fastpages_fastpages_1 ... done
Removing network fastpages_default
docker-compose up
Creating network "fastpages_default" with the default driver
Creating fastpages_jekyll_1    ... done
Creating fastpages_converter_1 ... done
Creating fastpages_fastpages_1 ... done
Creating fastpages_watcher_1   ... done
Creating fastpages_notebook_1  ... done
Attaching to fastpages_watcher_1, fastpages_converter_1, fastpages_fastpages_1, fastpages_notebook_1, fastpages_jekyll_1
fastpages_1  | Agent pid 11
converter_1  | Agent pid 11
converter_1  | === Running Locally: All assets expected to be in the directory /data ===
fastpages_1  | === Running Locally: All assets expected to be in the directory /data ===
watcher_1    | Traceback (most recent call last):
watcher_1    |   File "/usr/local/bin/watchmedo", line 8, in <module>
watcher_1    |     sys.exit(main())
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/watchmedo.py", line 581, in main
watcher_1    |     parser.dispatch()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/helpers.py", line 55, in dispatch
watcher_1    |     return dispatch(self, *args, **kwargs)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/dispatching.py", line 174, in dispatch
watcher_1    |     for line in lines:
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/dispatching.py", line 277, in _execute_command
watcher_1    |     for line in result:
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/argh/dispatching.py", line 231, in _call
watcher_1    |     result = function(namespace_obj)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/watchmedo.py", line 442, in shell_command
watcher_1    |     observe_with(observer, handler, args.directories, args.recursive)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/watchmedo.py", line 111, in observe_with
watcher_1    |     observer.start()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/api.py", line 256, in start
watcher_1    |     emitter.start()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/utils/__init__.py", line 93, in start
watcher_1    |     self.on_thread_start()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify.py", line 117, in on_thread_start
watcher_1    |     self._inotify = InotifyBuffer(path, self.watch.is_recursive)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
watcher_1    |     self._inotify = Inotify(path, recursive)
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 186, in __init__
watcher_1    |     Inotify._raise_error()
watcher_1    |   File "/usr/local/lib/python3.8/dist-packages/watchdog/observers/inotify_c.py", line 429, in _raise_error
watcher_1    |     raise OSError(err, os.strerror(err))
watcher_1    | OSError: [Errno 38] Function not implemented
```

**Comment by alexlenail** [comment]
@hamelsmu What do you advise to do about this issue?

**Comment by hamelsmu** [comment]
_NB: I am writing this comment on all open issues_

Thank you for posting this issue, and I'm really sorry I haven't gotten around to fixing this.  All of my time has been focused on [nbdev](https://github.com/fastai/nbdev).   In the new version of nbdev, we knew that we wanted to include blogging rather than it being a separate project.  We realized that [Quarto](https://quarto.org/), which the new version of nbdev is built on, is much better than fastpages.    Rather than keep this project going, we are recommending that people migrate to Quarto as we think that will be more powerful for users and is a much better tool for blogging. 

I've written a detailed [migration guide](https://nbdev.fast.ai/tutorials/blogging.html) with some tools that will hopefully make the process of switching much easier.  Overall I think it will be worth it for users.

My apologies again for not getting to this issue sooner.  Will close this issue with this PR https://github.com/fastai/fastpages/pull/657, where we are letting people know that we are deprecating this project.  Thanks again for your support and for using fastpages!  🙇🏽
